#!/bin/bash
bash /usr/local/Cellar/hadoop/3.3.0/sbin/stop-dfs.sh
bash /usr/local/Cellar/hadoop/3.3.0/sbin/stop-yarn.sh
echo "#************************************************#"
echo "#                  stort complite                #"
echo "#                   port: 9870                   #"
echo "#               hostname: localhost              #"
echo "#************************************************#"



